"""add all mvp tables

Revision ID: b263a8a2a052
Revises: a25253a68da6
Create Date: 2026-02-22 12:11:22.516542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b263a8a2a052'
down_revision: Union[str, Sequence[str], None] = 'a25253a68da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('diet_type', sa.Text(), nullable=False),
    sa.Column('plan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nutrition_avg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('pantry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantry_items_user_id'), 'pantry_items', ['user_id'], unique=False)
    op.create_table('user_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_signals_user_id'), 'user_signals', ['user_id'], unique=False)
    op.create_table('user_taste_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('favourite_cuisines', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('favourite_ingredients', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('favourite_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('disliked_signals', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_prep_time', sa.Integer(), nullable=True),
    sa.Column('actual_raw_ratio', sa.Float(), nullable=True),
    sa.Column('avg_weekly_plans', sa.Float(), nullable=True),
    sa.Column('recent_meal_names', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('top_search_terms', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('signal_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('generated_meals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Text(), nullable=False),
    sa.Column('meal_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('prep_minutes', sa.Integer(), nullable=True),
    sa.Column('saved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_meals_meal_plan_id'), 'generated_meals', ['meal_plan_id'], unique=False)
    op.create_index(op.f('ix_generated_meals_user_id'), 'generated_meals', ['user_id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_lists_user_id'), 'shopping_lists', ['user_id'], unique=False)
    op.create_table('user_recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('diet_type', sa.Text(), nullable=True),
    sa.Column('prep_minutes', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), server_default='user', nullable=False),
    sa.Column('origin_plan_id', sa.UUID(), nullable=True),
    sa.Column('origin_day', sa.Text(), nullable=True),
    sa.Column('origin_meal', sa.Text(), nullable=True),
    sa.Column('corpus_file_id', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['origin_plan_id'], ['meal_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_recipes_user_id'), 'user_recipes', ['user_id'], unique=False)
    op.execute(
        "CREATE INDEX idx_user_recipes_embedding ON user_recipes "
        "USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )
    op.alter_column('user_preferences', 'diet_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('user_preferences', 'calories_target',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_preferences', 'excluded_ingredients',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_preferences', 'excluded_ingredients',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True)
    op.alter_column('user_preferences', 'calories_target',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_preferences', 'diet_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.execute("DROP INDEX IF EXISTS idx_user_recipes_embedding")
    op.drop_index(op.f('ix_user_recipes_user_id'), table_name='user_recipes')
    op.drop_table('user_recipes')
    op.drop_index(op.f('ix_shopping_lists_user_id'), table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_generated_meals_user_id'), table_name='generated_meals')
    op.drop_index(op.f('ix_generated_meals_meal_plan_id'), table_name='generated_meals')
    op.drop_table('generated_meals')
    op.drop_table('user_taste_profiles')
    op.drop_index(op.f('ix_user_signals_user_id'), table_name='user_signals')
    op.drop_table('user_signals')
    op.drop_index(op.f('ix_pantry_items_user_id'), table_name='pantry_items')
    op.drop_table('pantry_items')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
